import type { Metadata } from 'next';
import StoreProvider from '@/components/StoreProvider';

import './globals.css';
import { Header } from '@/components/Header';
import { Navbar } from '@/components/Navbar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <StoreProvider>
                <body className="mx-auto border border-black max-w-[1200px]">
                    <Header />
                    <Navbar />
                    {children}
                </body>
            </StoreProvider>
        </html>
    );
}
