import type { Metadata } from 'next';
import StoreProvider from '@/components/StoreProvider';

import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <StoreProvider>
                <body>{children}</body>
            </StoreProvider>
        </html>
    );
}
